/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OrgsRouteImport } from "./routes/orgs";

const OrgsRoute = OrgsRouteImport.update({
	id: "/orgs",
	path: "/orgs",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
	id: "/api/auth/$",
	path: "/api/auth/$",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/orgs": typeof OrgsRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/orgs": typeof OrgsRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/orgs": typeof OrgsRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/orgs" | "/api/auth/$";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/orgs" | "/api/auth/$";
	id: "__root__" | "/" | "/orgs" | "/api/auth/$";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	OrgsRoute: typeof OrgsRoute;
	ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/orgs": {
			id: "/orgs";
			path: "/orgs";
			fullPath: "/orgs";
			preLoaderRoute: typeof OrgsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/auth/$": {
			id: "/api/auth/$";
			path: "/api/auth/$";
			fullPath: "/api/auth/$";
			preLoaderRoute: typeof ApiAuthSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	OrgsRoute: OrgsRoute,
	ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
