// This file was automatically generated by prisma-zero.
// You should NOT make any changes in this file as it will be overwritten.

import { boolean, createBuilder, createSchema, enumeration, number, relationships, string, table } from "@rocicorp/zero";

export type MATCH_TYPE = "LIMITED_OVERS" | "TEST";

export type MATCH_STATUS = "SCHEDULED" | "LIVE" | "COMPLETED" | "ABANDONED" | "CANCELLED";

export type TOSS_DECISION = "BAT" | "BOWL";

export type MATCH_RESULT = "WIN" | "TIE" | "NO_RESULT" | "ABANDONED" | "CANCELLED";

export type INNING_STATUS = "NOT_STARTED" | "LIVE" | "COMPLETED" | "DECLARED" | "FORFEITED";

export type DISMISSAL_KIND =
	| "BOWLED"
	| "CAUGHT"
	| "CAUGHT_AND_BOWLED"
	| "RUN_OUT"
	| "STUMPED"
	| "LBW"
	| "HIT_WICKET"
	| "MANKAD"
	| "RETIRED_OUT"
	| "RETIRED_HURT"
	| "OBSTRUCTING_FIELD"
	| "TIMED_OUT"
	| "HIT_BALL_TWICE";

export const userTable = table("User")
	.from("users")
	.columns({
		id: string(),
		name: string(),
		email: string(),
		emailVerified: boolean(),
		image: string().optional(),
		createdAt: number(),
		updatedAt: number(),
	})
	.primaryKey("id");

export const sessionTable = table("Session")
	.from("sessions")
	.columns({
		id: string(),
		expiresAt: number(),
		token: string(),
		createdAt: number(),
		updatedAt: number(),
		ipAddress: string().optional(),
		userAgent: string().optional(),
		activeOrganizationId: string().optional(),
		activeTeamId: string().optional(),
		userId: string(),
	})
	.primaryKey("id");

export const accountTable = table("Account")
	.from("accounts")
	.columns({
		id: string(),
		accountId: string(),
		providerId: string(),
		userId: string(),
		accessToken: string().optional(),
		refreshToken: string().optional(),
		idToken: string().optional(),
		accessTokenExpiresAt: number().optional(),
		refreshTokenExpiresAt: number().optional(),
		scope: string().optional(),
		password: string().optional(),
		createdAt: number(),
		updatedAt: number(),
	})
	.primaryKey("id");

export const verificationTable = table("Verification")
	.from("verifications")
	.columns({
		id: string(),
		identifier: string(),
		value: string(),
		expiresAt: number(),
		createdAt: number(),
		updatedAt: number(),
	})
	.primaryKey("id");

export const organizationTable = table("Organization")
	.from("organizations")
	.columns({
		id: string(),
		name: string(),
		slug: string(),
		logo: string().optional(),
		metadata: string().optional(),
		createdAt: number(),
	})
	.primaryKey("id");

export const memberTable = table("Member")
	.from("members")
	.columns({
		id: string(),
		role: string(),
		userId: string(),
		organizationId: string(),
		createdAt: number(),
	})
	.primaryKey("id");

export const invitationTable = table("Invitation")
	.from("invitations")
	.columns({
		id: string(),
		email: string(),
		role: string().optional(),
		status: string(),
		inviterId: string(),
		organizationId: string(),
		createdAt: number(),
		expiresAt: number(),
	})
	.primaryKey("id");

export const matchTable = table("Match")
	.from("matches")
	.columns({
		id: string(),
		organizationId: string(),
		matchNumber: number(),
		matchType: enumeration<MATCH_TYPE>(),
		status: enumeration<MATCH_STATUS>(),
		oversPerInning: number().optional(),
		teamAId: string(),
		teamBId: string(),
		tossWinnerTeamId: string().optional(),
		tossDecision: enumeration<TOSS_DECISION>().optional(),
		winnerTeamId: string().optional(),
		result: enumeration<MATCH_RESULT>().optional(),
		winMarginRuns: number().optional(),
		winMarginWickets: number().optional(),
		playerOfTheMatchId: string().optional(),
		startedAt: number().optional(),
		endedAt: number().optional(),
		createdAt: number(),
	})
	.primaryKey("id");

export const matchPlayerTable = table("MatchPlayer")
	.from("match_players")
	.columns({
		id: string(),
		organizationId: string(),
		matchId: string(),
		teamId: string(),
		playerId: string(),
		isCaptain: boolean(),
		isWicketKeeper: boolean(),
		isSubstitute: boolean(),
		createdAt: number(),
	})
	.primaryKey("id");

export const inningTable = table("Inning")
	.from("innings")
	.columns({
		id: string(),
		organizationId: string(),
		matchId: string(),
		inningNumber: number(),
		status: enumeration<INNING_STATUS>(),
		battingTeamId: string(),
		bowlingTeamId: string(),
		oversLimit: number().optional(),
		targetRuns: number().optional(),
		createdAt: number(),
	})
	.primaryKey("id");

export const ballTable = table("Ball")
	.from("balls")
	.columns({
		id: string(),
		organizationId: string(),
		inningId: string(),
		sequence: number(),
		batterId: string(),
		bowlerId: string(),
		nonStrikerId: string(),
		fielderId: string().optional(),
		secondaryFielderId: string().optional(),
		dismissedPlayerId: string().optional(),
		dismissalKind: enumeration<DISMISSAL_KIND>().optional(),
		runsOffBat: number(),
		wides: number(),
		noBalls: number(),
		byes: number(),
		legByes: number(),
		createdAt: number(),
	})
	.primaryKey("id");

export const playerTable = table("Player")
	.from("players")
	.columns({
		id: string(),
		organizationId: string(),
		userId: string().optional(),
		name: string(),
		image: string().optional(),
		createdAt: number(),
	})
	.primaryKey("id");

export const teamTable = table("Team")
	.from("teams")
	.columns({
		id: string(),
		organizationId: string(),
		name: string(),
		slug: string(),
		image: string().optional(),
		createdAt: number(),
	})
	.primaryKey("id");

export const teamPlayerTable = table("TeamPlayer")
	.from("team_players")
	.columns({
		id: string(),
		organizationId: string(),
		teamId: string(),
		playerId: string(),
		createdAt: number(),
	})
	.primaryKey("id");

export const userTableRelationships = relationships(userTable, ({ one, many }) => ({
	sessions: many({
		sourceField: ["id"],
		destField: ["userId"],
		destSchema: sessionTable,
	}),
	accounts: many({
		sourceField: ["id"],
		destField: ["userId"],
		destSchema: accountTable,
	}),
	members: many({
		sourceField: ["id"],
		destField: ["userId"],
		destSchema: memberTable,
	}),
	invitations: many({
		sourceField: ["id"],
		destField: ["inviterId"],
		destSchema: invitationTable,
	}),
	player: one({
		sourceField: ["id"],
		destField: ["userId"],
		destSchema: playerTable,
	}),
}));
export const sessionTableRelationships = relationships(sessionTable, ({ one }) => ({
	user: one({
		sourceField: ["userId"],
		destField: ["id"],
		destSchema: userTable,
	}),
}));
export const accountTableRelationships = relationships(accountTable, ({ one }) => ({
	user: one({
		sourceField: ["userId"],
		destField: ["id"],
		destSchema: userTable,
	}),
}));
export const organizationTableRelationships = relationships(organizationTable, ({ many }) => ({
	members: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: memberTable,
	}),
	invitations: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: invitationTable,
	}),
	players: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: playerTable,
	}),
	teams: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: teamTable,
	}),
	matches: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: matchTable,
	}),
	innings: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: inningTable,
	}),
	balls: many({
		sourceField: ["id"],
		destField: ["organizationId"],
		destSchema: ballTable,
	}),
}));
export const memberTableRelationships = relationships(memberTable, ({ one }) => ({
	user: one({
		sourceField: ["userId"],
		destField: ["id"],
		destSchema: userTable,
	}),
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
}));
export const invitationTableRelationships = relationships(invitationTable, ({ one }) => ({
	inviter: one({
		sourceField: ["inviterId"],
		destField: ["id"],
		destSchema: userTable,
	}),
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
}));
export const matchTableRelationships = relationships(matchTable, ({ one, many }) => ({
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
	teamA: one({
		sourceField: ["teamAId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	teamB: one({
		sourceField: ["teamBId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	tossWinnerTeam: one({
		sourceField: ["tossWinnerTeamId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	winnerTeam: one({
		sourceField: ["winnerTeamId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	playerOfTheMatch: one({
		sourceField: ["playerOfTheMatchId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
	innings: many({
		sourceField: ["id"],
		destField: ["matchId", "organizationId"],
		destSchema: inningTable,
	}),
	players: many({
		sourceField: ["id"],
		destField: ["matchId", "organizationId"],
		destSchema: matchPlayerTable,
	}),
}));
export const matchPlayerTableRelationships = relationships(matchPlayerTable, ({ one }) => ({
	match: one({
		sourceField: ["matchId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: matchTable,
	}),
	team: one({
		sourceField: ["teamId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	player: one({
		sourceField: ["playerId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
}));
export const inningTableRelationships = relationships(inningTable, ({ one, many }) => ({
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
	match: one({
		sourceField: ["matchId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: matchTable,
	}),
	battingTeam: one({
		sourceField: ["battingTeamId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	bowlingTeam: one({
		sourceField: ["bowlingTeamId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	balls: many({
		sourceField: ["id"],
		destField: ["inningId", "organizationId"],
		destSchema: ballTable,
	}),
}));
export const ballTableRelationships = relationships(ballTable, ({ one }) => ({
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
	inning: one({
		sourceField: ["inningId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: inningTable,
	}),
	batter: one({
		sourceField: ["batterId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
	bowler: one({
		sourceField: ["bowlerId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
	nonStriker: one({
		sourceField: ["nonStrikerId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
	fielder: one({
		sourceField: ["fielderId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
	secondaryFielder: one({
		sourceField: ["secondaryFielderId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
	dismissedPlayer: one({
		sourceField: ["dismissedPlayerId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
}));
export const playerTableRelationships = relationships(playerTable, ({ one, many }) => ({
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
	user: one({
		sourceField: ["userId"],
		destField: ["id"],
		destSchema: userTable,
	}),
	potmMatches: many({
		sourceField: ["id"],
		destField: ["playerOfTheMatchId", "organizationId"],
		destSchema: matchTable,
	}),
	teamMemberships: many({
		sourceField: ["id"],
		destField: ["playerId", "organizationId"],
		destSchema: teamPlayerTable,
	}),
	matchSelections: many({
		sourceField: ["id"],
		destField: ["playerId", "organizationId"],
		destSchema: matchPlayerTable,
	}),
	battingBalls: many({
		sourceField: ["id"],
		destField: ["batterId", "organizationId"],
		destSchema: ballTable,
	}),
	nonStrikerBalls: many({
		sourceField: ["id"],
		destField: ["nonStrikerId", "organizationId"],
		destSchema: ballTable,
	}),
	bowlingBalls: many({
		sourceField: ["id"],
		destField: ["bowlerId", "organizationId"],
		destSchema: ballTable,
	}),
	fieldingBalls: many({
		sourceField: ["id"],
		destField: ["fielderId", "organizationId"],
		destSchema: ballTable,
	}),
	secondaryFieldingBalls: many({
		sourceField: ["id"],
		destField: ["secondaryFielderId", "organizationId"],
		destSchema: ballTable,
	}),
	dismissedBalls: many({
		sourceField: ["id"],
		destField: ["dismissedPlayerId", "organizationId"],
		destSchema: ballTable,
	}),
}));
export const teamTableRelationships = relationships(teamTable, ({ one, many }) => ({
	organization: one({
		sourceField: ["organizationId"],
		destField: ["id"],
		destSchema: organizationTable,
	}),
	roster: many({
		sourceField: ["id"],
		destField: ["teamId", "organizationId"],
		destSchema: teamPlayerTable,
	}),
	matchTeamA: many({
		sourceField: ["id"],
		destField: ["teamAId", "organizationId"],
		destSchema: matchTable,
	}),
	matchTeamB: many({
		sourceField: ["id"],
		destField: ["teamBId", "organizationId"],
		destSchema: matchTable,
	}),
	tossWonMatches: many({
		sourceField: ["id"],
		destField: ["tossWinnerTeamId", "organizationId"],
		destSchema: matchTable,
	}),
	wonMatches: many({
		sourceField: ["id"],
		destField: ["winnerTeamId", "organizationId"],
		destSchema: matchTable,
	}),
	battingInnings: many({
		sourceField: ["id"],
		destField: ["battingTeamId", "organizationId"],
		destSchema: inningTable,
	}),
	bowlingInnings: many({
		sourceField: ["id"],
		destField: ["bowlingTeamId", "organizationId"],
		destSchema: inningTable,
	}),
	matchPlayers: many({
		sourceField: ["id"],
		destField: ["teamId", "organizationId"],
		destSchema: matchPlayerTable,
	}),
}));
export const teamPlayerTableRelationships = relationships(teamPlayerTable, ({ one }) => ({
	team: one({
		sourceField: ["teamId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: teamTable,
	}),
	player: one({
		sourceField: ["playerId", "organizationId"],
		destField: ["id", "organizationId"],
		destSchema: playerTable,
	}),
}));
/**
 * The Zero schema object.
 * This type is auto-generated from your Prisma schema definition.
 */
export const schema = createSchema({
	tables: [
		userTable,
		sessionTable,
		accountTable,
		verificationTable,
		organizationTable,
		memberTable,
		invitationTable,
		matchTable,
		matchPlayerTable,
		inningTable,
		ballTable,
		playerTable,
		teamTable,
		teamPlayerTable,
	],
	relationships: [
		userTableRelationships,
		sessionTableRelationships,
		accountTableRelationships,
		organizationTableRelationships,
		memberTableRelationships,
		invitationTableRelationships,
		matchTableRelationships,
		matchPlayerTableRelationships,
		inningTableRelationships,
		ballTableRelationships,
		playerTableRelationships,
		teamTableRelationships,
		teamPlayerTableRelationships,
	],
});

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Prisma schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Prisma schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Prisma schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql;
/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
	interface DefaultTypes {
		schema: Schema;
	}
}
